version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gatitos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
    ports:
      - "5432:5432"

  # Servicio web (API) estable
  web-stable:
    image: ghcr.io/santiaguitouwu/dds2_api:stable
    environment:
      DATABASE_URL: postgres://postgres:root@postgres:5432/gatitos
    deploy:
      replicas: 1  # Replicas del servicio API estable
    ports:
      - "8000:8000"

  # Servicio web (API) canary
  web-canary:
    image: ghcr.io/santiaguitouwu/dds2_api:canary
    environment:
      DATABASE_URL: postgres://postgres:root@postgres:5432/gatitos
    deploy:
      replicas: 1  # Solo 1 réplica para la versión canary
    ports:
      - "8001:8000"  # Exponer en un puerto diferente
    depends_on:
      - postgres

  # Servicio react (cliente) estable
  react-stable:
    image: ghcr.io/santiaguitouwu/dds2_cli:stable
    deploy:
      replicas: 1  # Replicas del servicio cliente estable
    ports:
      - "3000:3000"
    depends_on:
      - web-stable

  # Servicio react (cliente) canary
  react-canary:
    image: ghcr.io/santiaguitouwu/dds2_cli:canary
    deploy:
      replicas: 1  # Solo 1 réplica para la versión canary
    ports:
      - "3001:3000"  # Exponer en un puerto diferente
    depends_on:
      - web-canary

volumes:
  postgres_data:
