# Generated by Django 5.1.2 on 2024-12-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='estado_adopcion',
            field=models.BooleanField(),
        ),
    ]
