# Generated by Django 5.1.2 on 2024-12-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_pet_estado_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='estado_adopcion',
            field=models.BooleanField(default=False),
        ),
    ]
