name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run containers
        run: docker-compose up --build

      - name: Run Django tests
        run: docker-compose exec web python manage.py test

      - name: Run React tests
        run: docker-compose exec react npm run test

      - name: Stop and remove containers
        run: docker-compose down
