name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: gatitos
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: > 
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
          
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # BACK TEST
      - name: Install Django dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r ./petcareAPI/requirements.txt

      - name: Run Django tests
        working-directory: ./petcareAPI
        run: python manage.py test

    # TEST FRONT
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '16.x'

      - name: Install Node.js dependencies
        working-directory: ./petcareCLIENT
        run: npm install

      - name: Run React tests
        working-directory: ./petcareCLIENT
        run: npm run test
