name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # BACK TEST
      - name: Install Django dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r ./petcareAPI/requirements.txt

      - name: Run Django tests
        working-directory: ./petcareAPI
        run: python manage.py test

    # TEST FRONT
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '16.x'

      - name: Install Node.js dependencies
        working-directory: ./petcareCLIENT
        run: npm install

      - name: Run React tests
        working-directory: ./petcareCLIENT
        run: npm run test


