name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: gatitos
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
    
    env:
      DB_HOST: postgres  # Cambia esto a 'localhost' si es necesario

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Set environment variable for DB_HOST
        run: echo "DB_HOST=localhost" >> $GITHUB_ENV

      - name:
        run: echo "DB_HOST=localhost" >> $GITHUB_ENV

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h ${{ env.DB_HOST }} -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      # BACK TEST
      - name: Install Django dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r ./petcareAPI/requirements.txt
      
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
      
      - name: Run Django tests
        working-directory: ./petcareAPI
        run: python manage.py test

    # TEST FRONT
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '16.x'

      - name: Install Node.js dependencies
        working-directory: ./petcareCLIENT
        run: npm install

      - name: Run React tests
        working-directory: ./petcareCLIENT
        run: npm run test
