name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    create-docker-images:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Login to Github Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.TOKEN_CD}}

            - name: Build the docker image PETCARE_API_Stable
              run: |
                docker build ./petcareAPI --tag ghcr.io/santiaguitouwu/DDSII_API_Stable
                docker push ghcr.io/santiaguitouwu/DDSII_API

            - name: Build the docker image PETCARE_API_Canary
              run: |
                  docker build ./petcareAPI --tag ghcr.io/santiaguitouwu/DDSII_API_Canary
                  docker push ghcr.io/santiaguitouwu/DDSII_API
            
            - name: Build the docker image PETCARE_CLIENT_Stable
              run: |
                  docker build ./petcareCLIENT --tag ghcr.io/santiaguitouwu/DDSII_CLIENT_Stable
                  docker push ghcr.io/santiaguitouwu/DDSII_CLIENT

            - name: Build the docker image PETCARE_CLIENT_Stable
              run: |
                  docker build ./petcareCLIENT --tag ghcr.io/santiaguitouwu/DDSII_CLIENT_Stable
                  docker push ghcr.io/santiaguitouwu/DDSII_CLIENT

    deploy-on-AWS:
        needs: create-docker-images
        runs-on: ubuntu-latest       
        steps:
            - name: Install sshpass
              run: sudo apt-get install -y sshpass

            - name: Install SSH pass
              run:  |
                ssh -i ${{secrets.AWS_SSH_KEY}} ubuntu@ec2-18-216-190-163.us-east-2.compute.amazonaws.com
                cd /root/DDSII/
                docker pull ghcr.io/
            
            - name: Copy docker-compose.yml to AWS VM
              run: |
                 scp -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_KEY }} docker-compose.yml ubuntu@ec2-18-216-190-163.us-east-2.compute.amazonaws.com:/root/DDSII/
        
            - name: Run docker-compose on AWS VM
              run: |
                  ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_KEY }} ubuntu@your-ec2-public-ip 'docker stack deploy -c docker-compose.yml my_stack --detach=false'

